### ISSUE TITLE
Fix Core "do" Behavior in Data::Object::Export

### ISSUE THREAD

**Issue by alnewkirk** [iamalnewkirk/data-object#174]
https://github.com/iamalnewkirk/data-object/blob/a8e09d747b5b88ad87482257eb2ba21a8b38e694/lib/Data/Object/Export.pm#L104

Should be `return CORE::do($_[0]) if @_ < 2` because `CORE::do` behaves strangely when using `@_` from here.

**Comment by iamalnewkirk** [comment]
Fixed in #177
